### ISSUE TITLE
关于多接口请求的问题

### ISSUE THREAD

**Issue by createBean** [iostyle/ContinuousTrigger#1]
请问下，我有5个弹窗，每个弹窗都是一个接口，有些弹窗要根据接口返回的字段来判断显示与否，这种情况的我应该怎么样处理？

我看到demo中，是先写死所有要弹的窗，然后一个个弹出来。那我这种需要等接口返回数据进行处理的，应该怎么弄比较好  谢谢

**Comment by iostyle** [comment]
如果是阻塞模式的话，接口返回后判断为不需要展示的话，手动调用next方法即可

**Comment by iostyle** [comment]
这个项目设计的初衷就是为了解决这个场景，完全可以满足你的需求

**Comment by createBean** [comment]
哦哦，意思是注册还是按顺序去注册，然后根据接口返回的状态，去手动next


| |
singleleft
|
|
邮箱：singleleft@163.com
|

Signature is customized by Netease Mail Master

在2020年05月29日 11:07，iostyle 写道：

这个项目设计的初衷就是为了解决这个场景，完全可以满足你的需求

**Comment by iostyle** [comment]
> 哦哦，意思是注册还是按顺序去注册，然后根据接口返回的状态，去手动next | | singleleft | | 邮箱：singleleft@163.com | Signature is customized by Netease Mail Master 在2020年05月29日 11:07，iostyle 写道： 这个项目设计的初衷就是为了解决这个场景，完全可以满足你的需求 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应用于弹窗场景需要阻塞任务队列，在弹窗关闭后或者不需要弹窗的时候手动next即可，非阻塞任务则不需要

**Comment by createBean** [comment]
好的。谢谢
| |
singleleft
|
|
邮箱：singleleft@163.com
|

Signature is customized by Netease Mail Master

在2020年05月29日 11:11，iostyle 写道：

哦哦，意思是注册还是按顺序去注册，然后根据接口返回的状态，去手动next | | singleleft | | 邮箱：singleleft@163.com | Signature is customized by Netease Mail Master 在2020年05月29日 11:07，iostyle 写道： 这个项目设计的初衷就是为了解决这个场景，完全可以满足你的需求 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应用于弹窗场景需要阻塞任务队列，在弹窗关闭后或者不需要弹窗的时候手动next即可，非阻塞任务则不需要

**Comment by iostyle** [comment]
> 好的。谢谢 | | singleleft | | 邮箱：singleleft@163.com | Signature is customized by Netease Mail Master 在2020年05月29日 11:11，iostyle 写道： 哦哦，意思是注册还是按顺序去注册，然后根据接口返回的状态，去手动next | | singleleft | | 邮箱：singleleft@163.com | Signature is customized by Netease Mail Master 在2020年05月29日 11:07，iostyle 写道： 这个项目设计的初衷就是为了解决这个场景，完全可以满足你的需求 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 应用于弹窗场景需要阻塞任务队列，在弹窗关闭后或者不需要弹窗的时候手动next即可，非阻塞任务则不需要 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不用客气，欢迎反馈😄

**Comment by createBean** [comment]
注册的话，还是按顺序去注册，


| |
singleleft
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2020年05月29日 11:06，iostyle 写道：

如果是阻塞模式的话，接口返回后判断为不需要展示的话，手动调用next方法即可
