### ISSUE TITLE
这个问题处理了吗？

### ISSUE THREAD

**Issue by guominfang** [iostyle/ContinuousTrigger#4]
这个问题处理了吗？

 需求，同时检查APP更新和数据库更新，根据接口返回，是否弹出dialog提示，如下图接入方式，代码不工作

![image](https://user-images.githubusercontent.com/24568042/147081783-2bf24f10-f553-47f4-a51b-1565d36b172a.png)

_Originally posted by @guominfang in https://github.com/iostyle/ContinuousTrigger/issues/3#issuecomment-999480386_

**Comment by iostyle** [comment]
有尝试过断点调试嘛，卡在哪一步，是框架的问题的话可以给我回复描述一下，我会修复

**Comment by guominfang** [comment]
如上图所示，定义了两个弹窗，A：APP更新  B：数据库更新，

弹窗的顺序都是按照接口的异步回调，

B先回调了，但是定义的时候，是A 优先于B， 所以B不显示。但是等到A回调，A也不显示了

**Comment by iostyle** [comment]
> 如上图所示，定义了两个弹窗，A：APP更新 B：数据库更新，
> 
> 弹窗的顺序都是按照接口的异步回调，
> 
> 但是定义的时候，是规定，A在B之前，目前是 B先回调了， 所以B不显示。但是等到A回调，A也不显示了

你的代码里当B不显示的时候将trigger释放了呀，所以A才不显示了呀

**Comment by iostyle** [comment]
removeTriggerInstance(name: String, clear: Boolean) clear传入false即可

**Comment by iostyle** [comment]
你的代码流程也存在些许的问题，可以再好好思考一下

**Comment by iostyle** [comment]
框架如果有问题的话欢迎再提交issue
